
import java.awt.Dimension;
import java.awt.Toolkit;


public class loadScreen extends javax.swing.JFrame {

    /**
     * Creates new form mainProgFrame
     */
    public loadScreen() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        
        for (int i = 0;  i <= 100; i++) {
            try {
                Thread.sleep(40);
            } catch (InterruptedException ex) {
            }
            
            this.Loading.setText("analyzing text " + i + "%");
            this.Load.setValue(i);
            this.setVisible(true);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mpTitlePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Loading = new javax.swing.JLabel();
        Load = new javax.swing.JProgressBar();
        instruct = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mpTitlePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(mpTitlePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 50, 810, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Palenzuela\\Desktop\\GUI Photo Source\\techload.gif")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 480, 270));

        Loading.setFont(new java.awt.Font("WeblySleek UI Light", 0, 14)); // NOI18N
        Loading.setForeground(new java.awt.Color(255, 255, 255));
        Loading.setText("Loading...");
        jPanel1.add(Loading, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 480, 240, -1));

        Load.setBackground(new java.awt.Color(0, 153, 153));
        Load.setForeground(new java.awt.Color(0, 255, 255));
        Load.setBorderPainted(false);
        jPanel1.add(Load, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 710, -1));

        instruct.setBackground(new java.awt.Color(42, 46, 48));
        instruct.setForeground(new java.awt.Color(42, 46, 48));
        instruct.setIcon(new javax.swing.ImageIcon("C:\\Users\\Palenzuela\\Desktop\\GUI Photo Source\\blackbackground.png")); // NOI18N
        instruct.setText("jLabel1");
        jPanel1.add(instruct, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 730, 520));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 740, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JProgressBar Load;
    public javax.swing.JLabel Loading;
    public javax.swing.JLabel instruct;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel mpTitlePanel;
    // End of variables declaration//GEN-END:variables
}
